//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLanguage.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 测试多语言及区域 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为 null 或空字符串。 的本地化字符串。
        /// </summary>
        public static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须介于 {0} 和 {1} 之间。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_Between {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须为来自“{0}”枚举的值。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_Enum_Member {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Enum_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须大于 {0}。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_GreaterThan {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须大于或等于 {0}。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须小于 {0}。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_LessThan {
            get {
                return ResourceManager.GetString("Argument_Must_Be_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须小于或等于 {0}。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为空字符串。它必须为 null 或为非空字符串。 的本地化字符串。
        /// </summary>
        public static string Argument_Must_Be_Null_Or_Non_Empty {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Null_Or_Non_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument &apos;{0}&apos; cannot be null, empty or contain only white space. 的本地化字符串。
        /// </summary>
        public static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The associated metadata type for type &apos;{0}&apos; contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type. 的本地化字符串。
        /// </summary>
        public static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; must be public. 的本地化字符串。
        /// </summary>
        public static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain a public method named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0}.{1} could not be found. 的本地化字符串。
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”和“{1}”不匹配。 的本地化字符串。
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到名为{0}的属性。 的本地化字符串。
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid credit card number. 的本地化字符串。
        /// </summary>
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; does not exist in type &apos;{1}&apos; or is not public and static. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute.Method was not specified. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute method &apos;{0}&apos; in type &apos;{1}&apos; must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not convert the value of type &apos;{0}&apos; to &apos;{1}&apos; as expected by method {2}.{3}. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom validation type &apos;{0}&apos; must be public. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不被允许 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CustomValidationAttribute.ValidatorType was not specified. 的本地化字符串。
        /// </summary>
        public static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom DataType string cannot be null or empty. 的本地化字符串。
        /// </summary>
        public static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值“{1}”对字段{0}无效。 的本地化字符串。
        /// </summary>
        public static string DataTypeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("DataTypeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} property has not been set.  Use the {1} method to get the value. 的本地化字符串。
        /// </summary>
        public static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段{0}不是正确的邮箱格式 的本地化字符串。
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type provided for EnumDataTypeAttribute cannot be null. 的本地化字符串。
        /// </summary>
        public static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”需要表示枚举类型。 的本地化字符串。
        /// </summary>
        public static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field only accepts files with the following extensions: {1} 的本地化字符串。
        /// </summary>
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot retrieve property &apos;{0}&apos; because localization failed.  Type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length. 的本地化字符串。
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段必须是字符串或 最大长度为&apos;{1}&apos;的数组。 的本地化字符串。
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MetadataClassType cannot be null. 的本地化字符串。
        /// </summary>
        public static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinLengthAttribute must have a Length value that is zero or greater. 的本地化字符串。
        /// </summary>
        public static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段必须是字符串或 最小长度为&apos;{1}&apos;的数组。 的本地化字符串。
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid phone number. 的本地化字符串。
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must implement {1}. 的本地化字符串。
        /// </summary>
        public static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum value &apos;{0}&apos; must be greater than or equal to the minimum value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The minimum and maximum values must be set. 的本地化字符串。
        /// </summary>
        public static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The OperandType must be set when strings are used for minimum and maximum values. 的本地化字符串。
        /// </summary>
        public static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段值必须介于 {1} 和 {2} 之间 的本地化字符串。
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段值必须匹配正则表达式 &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须将模式设置为有效的正则表达式 的本地化字符串。
        /// </summary>
        public static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到用于远程验证的 url。 的本地化字符串。
        /// </summary>
        public static string RemoteAttribute_NoUrlFound {
            get {
                return ResourceManager.GetString("RemoteAttribute_NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”无效。 的本地化字符串。
        /// </summary>
        public static string RemoteAttribute_RemoteValidationFailed {
            get {
                return ResourceManager.GetString("RemoteAttribute_RemoteValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段是必须的。My 的本地化字符串。
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum length must be a nonnegative integer. 的本地化字符串。
        /// </summary>
        public static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段必须是字符串且最大长度为&apos;{1}&apos;的数组。 的本地化字符串。
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段必须是字符串且 长度必须介于&apos;{1}&apos; 到 &apos;{2}&apos;之间。 的本地化字符串。
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} with value &apos;{1}&apos; is not a string. Every key control parameter must be a string. 的本地化字符串。
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} is null. Every key control parameter must be a string. 的本地化字符串。
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key parameter at position {0} with value &apos;{1}&apos; occurs more than once. 的本地化字符串。
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of control parameters must be even. 的本地化字符串。
        /// </summary>
        public static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未授权 的本地化字符串。
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} field is not a valid fully-qualified http, https, or ftp URL. 的本地化字符串。
        /// </summary>
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Either ErrorMessageString or ErrorMessageResourceName must be set, but not both. 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context). 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute. 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;{0}&apos; on resource type &apos;{1}&apos; is not a string type. 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The resource type &apos;{0}&apos; does not have an accessible static property named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 字段 不被允许 的本地化字符串。
        /// </summary>
        public static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ValidationContext for the type &apos;{0}&apos;, member name &apos;{1}&apos; must provide the MethodInfo. 的本地化字符串。
        /// </summary>
        public static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A service of type &apos;{0}&apos; already exists in the container. 的本地化字符串。
        /// </summary>
        public static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入格式无效。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_DataType {
            get {
                return ResourceManager.GetString("ValidationDefault_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不匹配。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_EqualsTo {
            get {
                return ResourceManager.GetString("ValidationDefault_EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须是介于 {0} 和 {1} 之间的小数。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_FloatRange {
            get {
                return ResourceManager.GetString("ValidationDefault_FloatRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 值必须是介于 {1} 和 {2} 之间的整数。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_IntegerRange {
            get {
                return ResourceManager.GetString("ValidationDefault_IntegerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值无效。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_Regex {
            get {
                return ResourceManager.GetString("ValidationDefault_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大长度: {0}。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_StringLength {
            get {
                return ResourceManager.GetString("ValidationDefault_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串的长度必须是 {0} 到 {1} 个字符。 的本地化字符串。
        /// </summary>
        public static string ValidationDefault_StringLengthRange {
            get {
                return ResourceManager.GetString("ValidationDefault_StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The instance provided must match the ObjectInstance on the ValidationContext supplied. 的本地化字符串。
        /// </summary>
        public static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for property &apos;{0}&apos; must be of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
    }
}
