//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLanguage.MVCLang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLanguage.MVCLang.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 对控制器类型“{1}”的操作“{0}”的当前请求在下列操作方法之间不明确: {2} 的本地化字符串。
        /// </summary>
        public static string ActionMethodSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {1} 的 {0} 的本地化字符串。
        /// </summary>
        public static string ActionMethodSelector_AmbiguousMatchType {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须大于或等于 {0}。 的本地化字符串。
        /// </summary>
        public static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能同步执行异步操作方法“{0}”。 的本地化字符串。
        /// </summary>
        public static string AsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("AsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于在以下方法之间不明确，查找控制器类型“{1}”的方法“{0}”失败: {2} 的本地化字符串。
        /// </summary>
        public static string AsyncActionMethodSelector_AmbiguousMethodMatch {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_AmbiguousMethodMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能在控制器类型 {1} 上找到名为“{0}”的方法。 的本地化字符串。
        /// </summary>
        public static string AsyncActionMethodSelector_CouldNotFindMethod {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_CouldNotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用过提供的 IAsyncResult。 的本地化字符串。
        /// </summary>
        public static string AsyncCommon_AsyncResultAlreadyConsumed {
            get {
                return ResourceManager.GetString("AsyncCommon_AsyncResultAlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”的控制器必须创建 AsyncController 的子类或实现 IAsyncManagerContainer 接口。 的本地化字符串。
        /// </summary>
        public static string AsyncCommon_ControllerMustImplementIAsyncManagerContainer {
            get {
                return ResourceManager.GetString("AsyncCommon_ControllerMustImplementIAsyncManagerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的 IAsyncResult 对此方法无效。 的本地化字符串。
        /// </summary>
        public static string AsyncCommon_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时值必须是非负数或 Timeout.Infinite。 的本地化字符串。
        /// </summary>
        public static string AsyncCommon_InvalidTimeout {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法推断控制器“{0}”的区域名称，因为它没有命名空间。 的本地化字符串。
        /// </summary>
        public static string AttributeRouting_CouldNotInferAreaNameFromMissingNamespace {
            get {
                return ResourceManager.GetString("AttributeRouting_CouldNotInferAreaNameFromMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthorizeAttribute 不能在子操作缓存块中使用。 的本地化字符串。
        /// </summary>
        public static string AuthorizeAttribute_CannotUseWithinChildActionCache {
            get {
                return ResourceManager.GetString("AuthorizeAttribute_CannotUseWithinChildActionCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作“{0}”只能由子请求访问。 的本地化字符串。
        /// </summary>
        public static string ChildActionOnlyAttribute_MustBeInChildRequest {
            get {
                return ResourceManager.GetString("ChildActionOnlyAttribute_MustBeInChildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 {0} 必须是日期。 的本地化字符串。
        /// </summary>
        public static string ClientDataTypeModelValidatorProvider_FieldMustBeDate {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 {0} 必须是一个数字。 的本地化字符串。
        /// </summary>
        public static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由表中没有与提供的值匹配的路由。 的本地化字符串。
        /// </summary>
        public static string Common_NoRouteMatched {
            get {
                return ResourceManager.GetString("Common_NoRouteMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为 null 或为空。 的本地化字符串。
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到分部视图“{0}”或没有视图引擎支持搜索的位置。搜索了以下位置: {1} 的本地化字符串。
        /// </summary>
        public static string Common_PartialViewNotFound {
            get {
                return ResourceManager.GetString("Common_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性“{0}”不能为 null 或为空。 的本地化字符串。
        /// </summary>
        public static string Common_PropertyCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_PropertyCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到属性 {0}.{1}。 的本地化字符串。
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        public static string Common_TriState_False {
            get {
                return ResourceManager.GetString("Common_TriState_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        public static string Common_TriState_NotSet {
            get {
                return ResourceManager.GetString("Common_TriState_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        public static string Common_TriState_True {
            get {
                return ResourceManager.GetString("Common_TriState_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 必须从 {1} 派生 的本地化字符串。
        /// </summary>
        public static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值“{0}”无效。 的本地化字符串。
        /// </summary>
        public static string Common_ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("Common_ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到视图“{0}”或其母版视图，或没有视图引擎支持搜索的位置。搜索了以下位置: {1} 的本地化字符串。
        /// </summary>
        public static string Common_ViewNotFound {
            get {
                return ResourceManager.GetString("Common_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”和“{1}”不匹配。 的本地化字符串。
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到名为 {0} 的属性。 的本地化字符串。
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在控制器“{1}”上未找到公共操作方法“{0}”。 的本地化字符串。
        /// </summary>
        public static string Controller_UnknownAction {
            get {
                return ResourceManager.GetString("Controller_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在控制器“{0}”上找不到匹配的操作。如果控制器将 RouteAttribute 用于路由，但该控制器上没有与请求匹配的操作，则可能会发生这种情况。 的本地化字符串。
        /// </summary>
        public static string Controller_UnknownAction_NoActionName {
            get {
                return ResourceManager.GetString("Controller_UnknownAction_NoActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能更新类型“{0}”的模型。 的本地化字符串。
        /// </summary>
        public static string Controller_UpdateModel_UpdateUnsuccessful {
            get {
                return ResourceManager.GetString("Controller_UpdateModel_UpdateUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型为“{0}”的模型无效。 的本地化字符串。
        /// </summary>
        public static string Controller_Validate_ValidationFailed {
            get {
                return ResourceManager.GetString("Controller_Validate_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法执行 HttpContext 为 null 的控制器。 的本地化字符串。
        /// </summary>
        public static string ControllerBase_CannotExecuteWithNullHttpContext {
            get {
                return ResourceManager.GetString("ControllerBase_CannotExecuteWithNullHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能使用控制器“{0}”的单个实例处理多个请求。如果正在使用自定义控制器工厂，请确保它为每个请求创建该控制器的新实例。 的本地化字符串。
        /// </summary>
        public static string ControllerBase_CannotHandleMultipleRequests {
            get {
                return ResourceManager.GetString("ControllerBase_CannotHandleMultipleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试创建 IControllerFactory“{0}”时出错。请确保控制器工厂具有公共的无参数构造函数。 的本地化字符串。
        /// </summary>
        public static string ControllerBuilder_ErrorCreatingControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_ErrorCreatingControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IControllerFactory“{0}”未对名称“{1}”返回控制器。 的本地化字符串。
        /// </summary>
        public static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器工厂类型“{0}”必须实现 IControllerFactory 接口。 的本地化字符串。
        /// </summary>
        public static string ControllerBuilder_MissingIControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_MissingIControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未创建在“{0}”找到的视图。 的本地化字符串。
        /// </summary>
        public static string CshtmlView_ViewCouldNotBeCreated {
            get {
                return ResourceManager.GetString("CshtmlView_ViewCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”处的视图必须派生自 WebViewPage 或 WebViewPage&lt;TModel&gt;。 的本地化字符串。
        /// </summary>
        public static string CshtmlView_WrongViewBase {
            get {
                return ResourceManager.GetString("CshtmlView_WrongViewBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 具有 {1} 的 DisplayColumn 特性，但属性 {1} 不存在。 的本地化字符串。
        /// </summary>
        public static string DataAnnotationsModelMetadataProvider_UnknownProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 具有 {1} 的 DisplayColumn 特性，但属性 {1} 没有公共 getter。 的本地化字符串。
        /// </summary>
        public static string DataAnnotationsModelMetadataProvider_UnreadableProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnreadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 必须有接受类型 {1}、{2} 和 {3} 的三个参数的公共构造函数。 的本地化字符串。
        /// </summary>
        public static string DataAnnotationsModelValidatorProvider_ConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 必须具有可以接受两个 {1} 和 {2} 类型参数的公共构造函数。 的本地化字符串。
        /// </summary>
        public static string DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到多个与名为“{0}”的控制器匹配的类型。如果为此请求提供服务的路由没有指定命名空间以搜索与此请求相匹配的控制器，则会发生这种情况。如果是这样，请通过调用带有 &apos;namespaces&apos; 参数的 &quot;MapRoute&quot; 方法的重载来注册此路由。{2}{2}“{0}”请求找到下列匹配的控制器:{1} 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到多个与名为“{0}”的控制器匹配的类型。如果为此请求(“{1}”)提供服务的路由没有指定命名空间以搜索与此请求相匹配的控制器，则会发生这种情况。如果是这样，请通过调用带有 &apos;namespaces&apos; 参数的 &quot;MapRoute&quot; 方法的重载来注册此路由。{3}{3}“{0}”请求找到下列匹配的控制器:{2} 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到了多个与 URL 匹配的控制器类型。如果多个控制器上的特性路由与请求的 URL 匹配，则可能会发生这种情况。{1}{1}请求已找到下列匹配的控制器类型: {0} 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_DirectRouteAmbiguous {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_DirectRouteAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试创建“{0}”类型的控制器时出错。请确保控制器具有无参数公共构造函数。 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_ErrorCreatingController {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ErrorCreatingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到路径“{0}”的控制器或该控制器未实现 IController。 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_NoControllerFound {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器类型“{0}”必须实现 IController。 的本地化字符串。
        /// </summary>
        public static string DefaultControllerFactory_TypeDoesNotSubclassControllerBase {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_TypeDoesNotSubclassControllerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于激活约束类型“{0}”的构造函数不明确。找到包含以下数目的参数的多个构造函数: {1}。 的本地化字符串。
        /// </summary>
        public static string DefaultInlineConstraintResolver_AmbiguousCtors {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_AmbiguousCtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到约束类型为“{0}”且包含以下数目的参数的构造函数: {1}。 的本地化字符串。
        /// </summary>
        public static string DefaultInlineConstraintResolver_CouldNotFindCtor {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_CouldNotFindCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射到约束键“{1}”的约束类型“{0}”必须实现 IRouteConstraint 接口。 的本地化字符串。
        /// </summary>
        public static string DefaultInlineConstraintResolver_TypeNotConstraint {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_TypeNotConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值“{0}”对于 {1} 无效。 的本地化字符串。
        /// </summary>
        public static string DefaultModelBinder_ValueInvalid {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值是必需的。 的本地化字符串。
        /// </summary>
        public static string DefaultModelBinder_ValueRequired {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeSpan 值的记号数必须大于或等于 0。 的本地化字符串。
        /// </summary>
        public static string DefaultViewLocationCache_NegativeTimeSpan {
            get {
                return ResourceManager.GetString("DefaultViewLocationCache_NegativeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 似乎未实现 Microsoft.Practices.ServiceLocation.IServiceLocator。 的本地化字符串。
        /// </summary>
        public static string DependencyResolver_DoesNotImplementICommonServiceLocator {
            get {
                return ResourceManager.GetString("DependencyResolver_DoesNotImplementICommonServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前请求在下列操作方法之间不明确: {0} 的本地化字符串。
        /// </summary>
        public static string DirectRoute_AmbiguousMatch {
            get {
                return ResourceManager.GetString("DirectRoute_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作方法的直接路由不能使用参数 &quot;action&quot;。若要为操作创建路由，请指定文字路径来代替此参数。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_InvalidParameter_Action {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接路由不能使用参数 &quot;controller&quot;。若要为控制器创建路由，请指定文字路径来代替此参数。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_InvalidParameter_Controller {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由没有任何关联的操作描述符。路由要求每个直接路由都映射到一组非空操作。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_MissingActionDescriptors {
            get {
                return ResourceManager.GetString("DirectRoute_MissingActionDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由没有关联的控制器描述符。路由要求每个直接路由都映射到单个控制器。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_MissingControllerDescriptor {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由没有关联的控制器类型。路由要求每个直接路由都映射到单个控制器类型。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_MissingControllerType {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接路由不支持按路由路由处理程序。 的本地化字符串。
        /// </summary>
        public static string DirectRoute_RouteHandlerNotSupported {
            get {
                return ResourceManager.GetString("DirectRoute_RouteHandlerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModelType 属性不能为 null。 的本地化字符串。
        /// </summary>
        public static string EnumHelper_InvalidMetadataParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidMetadataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持类型“{0}”。 的本地化字符串。
        /// </summary>
        public static string EnumHelper_InvalidParameterType {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的值参数类型“{0}”。必须与类型参数“{1}”匹配。 的本地化字符串。
        /// </summary>
        public static string EnumHelper_InvalidValueParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidValueParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”未从 Exception 继承。 的本地化字符串。
        /// </summary>
        public static string ExceptionViewAttribute_NonExceptionType {
            get {
                return ResourceManager.GetString("ExceptionViewAttribute_NonExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式编译器无法计算索引器表达式“{0}”，因为后者引用的模型参数“{1}”不可用。 的本地化字符串。
        /// </summary>
        public static string ExpressionHelper_InvalidIndexerExpression {
            get {
                return ResourceManager.GetString("ExpressionHelper_InvalidIndexerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 必须大于或等于 -1。 的本地化字符串。
        /// </summary>
        public static string FilterAttribute_OrderOutOfRange {
            get {
                return ResourceManager.GetString("FilterAttribute_OrderOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给定的筛选器实例必须实现以下一个或多个筛选器接口: {0}、{1}、{2}、{3}、{4}。 的本地化字符串。
        /// </summary>
        public static string GlobalFilterCollection_UnsupportedFilterInstance {
            get {
                return ResourceManager.GetString("GlobalFilterCollection_UnsupportedFilterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持 GET 和 POST HTTP 方法。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_InvalidHttpMethod {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持指定的 HttpVerbs 值。支持的值为 Delete、Head、Put、Options 和 Patch。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_InvalidHttpVerb {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在具有键“{0}”的“{1}”类型的 ViewData 项。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在允许多重选择时，参数“{0}”必须等于某个 IEnumerable。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_SelectExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("HtmlHelper_SelectExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须大于或等于零。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_TextAreaParameterOutOfRange {
            get {
                return ResourceManager.GetString("HtmlHelper_TextAreaParameterOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 具有键“{0}”的 ViewData 项属于类型“{1}”，但它必须属于类型“{2}”。 的本地化字符串。
        /// </summary>
        public static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型为“{0}”的内联约束解析程序无法解析以下内联约束:“{1}”。 的本地化字符串。
        /// </summary>
        public static string HttpRouteBuilder_CouldNotResolveConstraint {
            get {
                return ResourceManager.GetString("HttpRouteBuilder_CouldNotResolveConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该键不符合 JQuery 语法，因为它缺少右括号。 的本地化字符串。
        /// </summary>
        public static string JQuerySyntaxMissingClosingBracket {
            get {
                return ResourceManager.GetString("JQuerySyntaxMissingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此请求已被阻止，因为当用在 GET 请求中时，会将敏感信息透漏给第三方网站。若要允许 GET 请求，请将 JsonRequestBehavior 设置为 AllowGet。 的本地化字符串。
        /// </summary>
        public static string JsonRequest_GetNotAllowed {
            get {
                return ResourceManager.GetString("JsonRequest_GetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON 请求太大，无法反序列化。 的本地化字符串。
        /// </summary>
        public static string JsonValueProviderFactory_RequestTooLarge {
            get {
                return ResourceManager.GetString("JsonValueProviderFactory_RequestTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试创建 IModelBinder“{0}”时出错。请确保联编程序具有公共的无参数构造函数。 的本地化字符串。
        /// </summary>
        public static string ModelBinderAttribute_ErrorCreatingModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_ErrorCreatingModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”未实现 IModelBinder 接口。 的本地化字符串。
        /// </summary>
        public static string ModelBinderAttribute_TypeNotIModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_TypeNotIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”包含多个从 CustomModelBinderAttribute 继承的特性。 的本地化字符串。
        /// </summary>
        public static string ModelBinderDictionary_MultipleAttributes {
            get {
                return ResourceManager.GetString("ModelBinderDictionary_MultipleAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此属性 setter 已过时，因为其值现在是从 ModelMetadata.Model 派生的。 的本地化字符串。
        /// </summary>
        public static string ModelMetadata_PropertyNotSettable {
            get {
                return ResourceManager.GetString("ModelMetadata_PropertyNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此构造函数已过时，因为它的功能现已由 MvcForm(ViewContext) 实现。 的本地化字符串。
        /// </summary>
        public static string MvcForm_ConstructorObsolete {
            get {
                return ResourceManager.GetString("MvcForm_ConstructorObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当使用“{0}”关键字时不允许使用“inherits”关键字。 的本地化字符串。
        /// </summary>
        public static string MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”关键字必须在同一行上后跟一个类型名称。 的本地化字符串。
        /// </summary>
        public static string MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个文件中仅允许使用一条“{0}”语句。 的本地化字符串。
        /// </summary>
        public static string MvcRazorCodeParser_OnlyOneModelStatementIsAllowed {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_OnlyOneModelStatementIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配的路由不包括所需的“controller”路由值。 的本地化字符串。
        /// </summary>
        public static string MvcRouteHandler_RouteValuesHasNoController {
            get {
                return ResourceManager.GetString("MvcRouteHandler_RouteValuesHasNoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许对已缓存的子操作的子操作使用 OutputCacheAttribute。 的本地化字符串。
        /// </summary>
        public static string OutputCacheAttribute_CannotNestChildCache {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_CannotNestChildCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子操作的 OutputCacheAttribute 仅支持 Duration、VaryByCustom 和 VaryByParam 值。请不要为子操作设置 CacheProfile、Location、NoStore、SqlDependency、VaryByContentEncoding 或 VaryByHeader 值。 的本地化字符串。
        /// </summary>
        public static string OutputCacheAttribute_ChildAction_UnsupportedSetting {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_ChildAction_UnsupportedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 必须为正数。 的本地化字符串。
        /// </summary>
        public static string OutputCacheAttribute_InvalidDuration {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VaryByParam 必须是“*”、“none”或分号分隔的键列表。 的本地化字符串。
        /// </summary>
        public static string OutputCacheAttribute_InvalidVaryByParam {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidVaryByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许子操作执行重定向操作。 的本地化字符串。
        /// </summary>
        public static string RedirectAction_CannotRedirectInChildAction {
            get {
                return ResourceManager.GetString("RedirectAction_CannotRedirectInChildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为类型“{1}”的实例方法“{0}”创建描述符，因为该类型不是从 ControllerBase 派生的。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能对控制器“{1}”调用操作方法“{0}”，因为参数“{2}”是通过引用传递的。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能对控制器“{1}”调用操作方法“{0}”，因为此操作方法是泛型方法。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallOpenGenericMethods {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallOpenGenericMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法对控制器“{1}”调用操作方法“{0}”，因为该操作方法为静态方法。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_CannotCallStaticMethod {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于“{3}”中方法“{2}”的不可以为 null 的类型“{1}”的参数“{0}”，参数字典包含一个 null 项。可选参数必须为引用类型、可以为 null 的类型或声明为可选参数。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于“{3}”中方法“{2}”的类型“{1}”的参数“{0}”，参数字典不包含对应的项。对于包括具有 null 值的参数在内的每个参数，字典都必须包含一项。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterNotInDictionary {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterNotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于“{2}”中方法“{1}”的参数“{0}”，参数字典包含无效项。字典包含一个类型“{3}”的值，但参数需要的是类型“{4}”的值。 的本地化字符串。
        /// </summary>
        public static string ReflectedActionDescriptor_ParameterValueHasWrongType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterValueHasWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法“{1}”的参数“{0}”包含多个从 CustomModelBinderAttribute 继承的特性。 的本地化字符串。
        /// </summary>
        public static string ReflectedParameterBindingInfo_MultipleConverterAttributes {
            get {
                return ResourceManager.GetString("ReflectedParameterBindingInfo_MultipleConverterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到用于远程验证的 url。 的本地化字符串。
        /// </summary>
        public static string RemoteAttribute_NoUrlFound {
            get {
                return ResourceManager.GetString("RemoteAttribute_NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”无效。 的本地化字符串。
        /// </summary>
        public static string RemoteAttribute_RemoteValidationFailed {
            get {
                return ResourceManager.GetString("RemoteAttribute_RemoteValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能通过 SSL 访问请求的资源。 的本地化字符串。
        /// </summary>
        public static string RequireHttpsAttribute_MustUseSsl {
            get {
                return ResourceManager.GetString("RequireHttpsAttribute_MustUseSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含多个节(例如文本节或参数)的路径段不能包含 catch-all 参数。 的本地化字符串。
        /// </summary>
        public static string Route_CannotHaveCatchAllInMultiSegment {
            get {
                return ResourceManager.GetString("Route_CannotHaveCatchAllInMultiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径段不能包含两个连续参数。必须使用 &quot;/&quot; 或文本字符串分隔它们。 的本地化字符串。
        /// </summary>
        public static string Route_CannotHaveConsecutiveParameters {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由模板分隔符 &quot;/&quot; 不能连续出现。必须使用参数或文本值分隔它。 的本地化字符串。
        /// </summary>
        public static string Route_CannotHaveConsecutiveSeparators {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 catch-all 参数只能作为路由模板的最后一个段出现。 的本地化字符串。
        /// </summary>
        public static string Route_CatchAllMustBeLast {
            get {
                return ResourceManager.GetString("Route_CatchAllMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带有路由模板“{1}”的路由上的约束项“{0}”必须包含字符串值或属于实现“{2}”的类型。 的本地化字符串。
        /// </summary>
        public static string Route_InvalidConstraint {
            get {
                return ResourceManager.GetString("Route_InvalidConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由参数名称“{0}”无效。路由参数名称必须非空，并且不能包含以下字符: &quot;{{&quot;,&quot;}}&quot;、&quot;/&quot;、&quot;?&quot; 的本地化字符串。
        /// </summary>
        public static string Route_InvalidParameterName {
            get {
                return ResourceManager.GetString("Route_InvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由模板不能以 &quot;/&quot; 或 &quot;~&quot; 字符开头，并且不能包含 &quot;?&quot; 字符。 的本地化字符串。
        /// </summary>
        public static string Route_InvalidRouteTemplate {
            get {
                return ResourceManager.GetString("Route_InvalidRouteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此路径段中存在不完整的参数:“{0}”。请检查每个 &quot;{{&quot; 字符是否都有匹配的 &quot;}}&quot; 字符。 的本地化字符串。
        /// </summary>
        public static string Route_MismatchedParameter {
            get {
                return ResourceManager.GetString("Route_MismatchedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由参数名称“{0}”在路由模板中出现了多次。 的本地化字符串。
        /// </summary>
        public static string Route_RepeatedParameter {
            get {
                return ResourceManager.GetString("Route_RepeatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为“{2}”的控制器上名为“{1}”的路由区域的前缀“{0}”不能以正斜杠结尾。 的本地化字符串。
        /// </summary>
        public static string RouteAreaPrefix_CannotEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteAreaPrefix_CannotEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为“{1}”的控制器上的路由前缀“{0}”不能以正斜杠开头或结尾。 的本地化字符串。
        /// </summary>
        public static string RoutePrefix_CannotStartOrEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotStartOrEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅支持一个路由前缀特性。请从“{0}”类型的控制器中删除额外的特性。 的本地化字符串。
        /// </summary>
        public static string RoutePrefix_CannotSupportMultiRoutePrefix {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotSupportMultiRoutePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”类型的控制器上的路由前缀特性中的属性 &quot;prefix&quot; 不能为 null。 的本地化字符串。
        /// </summary>
        public static string RoutePrefix_PrefixCannotBeNull {
            get {
                return ResourceManager.GetString("RoutePrefix_PrefixCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名为“{2}”的控制器上名为“{1}”的操作上的路由模板“{0}”不能以正斜杠开头。 的本地化字符串。
        /// </summary>
        public static string RouteTemplate_CannotStart_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteTemplate_CannotStart_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法确定表达式“{0}”的 ModelMetadata。 的本地化字符串。
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterNoMetadata {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法确定表达式“{0}”的类型。 的本地化字符串。
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterNoModelType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持返回类型“{0}”。 的本地化字符串。
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持返回类型“{0}”。类型必须具有“{1}”特性。 的本地化字符串。
        /// </summary>
        public static string SelectExtensions_InvalidExpressionParameterTypeHasFlags {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterTypeHasFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SessionStateTempDataProvider 类需要启用会话状态。 的本地化字符串。
        /// </summary>
        public static string SessionStateTempDataProvider_SessionStateDisabled {
            get {
                return ResourceManager.GetString("SessionStateTempDataProvider_SessionStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在解析程序以及 {1} 的自定义注册提供程序中各找到一个 {0} 实例。请仅设置其中的一个。 的本地化字符串。
        /// </summary>
        public static string SingleServiceResolver_CannotRegisterTwoInstances {
            get {
                return ResourceManager.GetString("SingleServiceResolver_CannotRegisterTwoInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由集合中已存在名称为“{0}”的路由。路由名称必须唯一。
        ///
        ///重复项:
        ///{1}
        ///{2} 的本地化字符串。
        /// </summary>
        public static string SubRouteCollection_DuplicateRouteName {
            get {
                return ResourceManager.GetString("SubRouteCollection_DuplicateRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个跨过同步上下文的操作失败。有关更多信息，请参见内部异常。 的本地化字符串。
        /// </summary>
        public static string SynchronizationContextUtil_ExceptionThrown {
            get {
                return ResourceManager.GetString("SynchronizationContextUtil_ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步操作方法“{0}”返回了一个无法同步执行的 Task。 的本地化字符串。
        /// </summary>
        public static string TaskAsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("TaskAsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到类型 {0} 的适当模板。 的本地化字符串。
        /// </summary>
        public static string TemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("TemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板只能用于字段访问、属性访问、一维数组索引或单参数自定义索引器表达式。 的本地化字符串。
        /// </summary>
        public static string TemplateHelpers_TemplateLimitations {
            get {
                return ResourceManager.GetString("TemplateHelpers_TemplateLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 Collection 模板一起使用的“{0}”类型的对象未实现 System.IEnumerable。 的本地化字符串。
        /// </summary>
        public static string Templates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("Templates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件自动生成。请不要修改此文件的内容。 的本地化字符串。
        /// </summary>
        public static string TypeCache_DoNotModify {
            get {
                return ResourceManager.GetString("TypeCache_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 对象类型“{1}”。 的本地化字符串。
        /// </summary>
        public static string TypeHelpers_CannotCreateInstance {
            get {
                return ResourceManager.GetString("TypeHelpers_CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} 不能返回 null。 的本地化字符串。
        /// </summary>
        public static string TypeMethodMustNotReturnNull {
            get {
                return ResourceManager.GetString("TypeMethodMustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元数据内部的模型对象声明与 {0} 兼容，但实际与 {1} 兼容。 的本地化字符串。
        /// </summary>
        public static string ValidatableObjectAdapter_IncompatibleType {
            get {
                return ResourceManager.GetString("ValidatableObjectAdapter_IncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从类型“{0}”到类型“{1}”的参数转换失败。有关更多信息，请参见内部异常。 的本地化字符串。
        /// </summary>
        public static string ValueProviderResult_ConversionThrew {
            get {
                return ResourceManager.GetString("ValueProviderResult_ConversionThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从类型“{0}”到类型“{1}”的参数转换失败，因为没有类型转换器可以在这些类型之间转换。 的本地化字符串。
        /// </summary>
        public static string ValueProviderResult_NoConverterExists {
            get {
                return ResourceManager.GetString("ValueProviderResult_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入字典的模型项为 null，但此字典需要类型“{0}”的非 null 模型项。 的本地化字符串。
        /// </summary>
        public static string ViewDataDictionary_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ViewDataDictionary_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入字典的模型项的类型为“{0}”，但此字典需要类型“{1}”的模型项。 的本地化字符串。
        /// </summary>
        public static string ViewDataDictionary_WrongTModelType {
            get {
                return ResourceManager.GetString("ViewDataDictionary_WrongTModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewMasterPage 只能与派生自 ViewPage 或 ViewPage&lt;TModel&gt; 的内容页一起使用。 的本地化字符串。
        /// </summary>
        public static string ViewMasterPage_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewMasterPage_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子请求执行失败。有关更多信息，请检查 InnerException。 的本地化字符串。
        /// </summary>
        public static string ViewPageHttpHandlerWrapper_ExceptionOccurred {
            get {
                return ResourceManager.GetString("ViewPageHttpHandlerWrapper_ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewStartPage 只能与派生自 WebViewPage 或其他 ViewStartPage 的页一起使用。 的本地化字符串。
        /// </summary>
        public static string ViewStartPage_RequiresMvcRazorView {
            get {
                return ResourceManager.GetString("ViewStartPage_RequiresMvcRazorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewUserControl“{0}”找不到 IViewDataContainer 对象。ViewUserControl 必须位于 ViewPage、ViewMasterPage 或另一个 ViewUserControl 中。 的本地化字符串。
        /// </summary>
        public static string ViewUserControl_RequiresViewDataProvider {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewUserControl 只能在派生自 ViewPage 或 ViewPage&lt;TModel&gt; 的页中使用。 的本地化字符串。
        /// </summary>
        public static string ViewUserControl_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当视图为 ViewUserControl 时不能指定母版名称。 的本地化字符串。
        /// </summary>
        public static string WebFormViewEngine_UserControlCannotHaveMaster {
            get {
                return ResourceManager.GetString("WebFormViewEngine_UserControlCannotHaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”处的视图必须派生自 ViewPage、ViewPage&lt;TModel&gt;、ViewUserControl 或 ViewUserControl&lt;TModel&gt;。 的本地化字符串。
        /// </summary>
        public static string WebFormViewEngine_WrongViewBase {
            get {
                return ResourceManager.GetString("WebFormViewEngine_WrongViewBase", resourceCulture);
            }
        }
    }
}
