// <auto-generated />
namespace TestAreaDemo.Areas.Movie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddActor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActor));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050700584_AddActor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
